pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/gordonan3/mlops_practice.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'pip3 install pandas scikit-learn numpy joblib'
            }
        }
        stage('Prepare Environment') {
            steps {
                sh 'mkdir -p train test test_scaled train_scaled'
            }
        }
        stage('Fetch Data') {
            steps {
                sh 'python3 lab2/data_creation.py'
            }
        }
        stage('Preprocess Data') {
            steps {
                sh 'python3 lab2/data_preprocessing.py'
            }
        }
        stage('Train Model') {
            steps {
                sh 'python3 lab2/model_preparation.py'
            }
        }
        stage('Test Model') {
            steps {
                sh 'python3 lab2/model_testing.py'
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/train/*.csv, **/test/*.csv, **/test_scaled/*.csv, **/train_scaled/*.csv', allowEmptyArchive: true
        }
    }
}
